import type { Email } from '@/types/mail'

export const sampleEmails: Email[] = [
  {
    id: 'email_bill_due',
    sender: 'Pacific Utilities <billing@pacificutilities.example>',
    subject: 'Payment due for your April utility bill',
    body: 'Your April utility bill is due on May 5. Please submit payment before the due date to avoid a late fee.',
    date: '2026-04-29T15:20:00.000Z',
    direction: 'inbound',
    labels: ['Bills', 'Finance'],
  },
  {
    id: 'email_permission_slip',
    sender: 'Lincoln Elementary <office@lincolnelementary.example>',
    subject: 'Field trip permission slip due Friday',
    body: 'Please sign and return the attached permission slip for the science museum field trip by Friday morning.',
    date: '2026-04-29T14:05:00.000Z',
    direction: 'inbound',
    labels: ['School', 'Family'],
  },
  {
    id: 'email_delivery_issue',
    sender: 'Northstar Delivery <support@northstardelivery.example>',
    subject: 'Action required: delivery address issue',
    body: 'We could not complete delivery because the apartment number was missing. Reply with the corrected address within 24 hours.',
    date: '2026-04-29T13:10:00.000Z',
    direction: 'inbound',
    labels: ['Shipping'],
  },
  {
    id: 'email_event_rsvp',
    sender: 'Avery Kim <avery@neighborhood.example>',
    subject: 'RSVP for Saturday community dinner',
    body: 'Can you let me know by Thursday whether you can attend the community dinner this Saturday?',
    date: '2026-04-29T12:30:00.000Z',
    direction: 'inbound',
    labels: ['Events'],
  },
  {
    id: 'email_work_follow_up',
    sender: 'Jordan Lee <jordan@brightline.example>',
    subject: 'Follow-up on Q2 launch notes',
    body: 'Please review the Q2 launch notes and send your edits before our planning meeting tomorrow.',
    date: '2026-04-29T11:45:00.000Z',
    direction: 'inbound',
    labels: ['Work'],
  },
  {
    id: 'email_doctor_form',
    sender: 'Willow Creek Clinic <forms@willowcreekclinic.example>',
    subject: 'Complete intake form before your appointment',
    body: 'Your appointment is scheduled for May 3. Complete the intake form online at least 24 hours before arrival.',
    date: '2026-04-29T10:15:00.000Z',
    direction: 'inbound',
    labels: ['Health'],
  },
  {
    id: 'email_subscription_renewal',
    sender: 'CloudNotes <billing@cloudnotes.example>',
    subject: 'Your annual subscription renews soon',
    body: 'Your CloudNotes annual plan renews on May 8. Review your plan or update payment details before renewal.',
    date: '2026-04-28T18:40:00.000Z',
    direction: 'inbound',
    labels: ['Subscriptions'],
  },
  {
    id: 'email_newsletter',
    sender: 'The Product Brief <newsletter@productbrief.example>',
    subject: 'This week in AI productivity tools',
    body: 'Read our roundup of new product releases, workflow ideas, and interviews with teams adopting AI assistants.',
    date: '2026-04-28T16:25:00.000Z',
    direction: 'inbound',
    labels: ['Newsletter'],
  },
  {
    id: 'email_promotion',
    sender: 'Trail Supply Co. <deals@trailsupply.example>',
    subject: 'Spring sale: 30% off backpacks',
    body: 'Shop our spring sale this week and save on backpacks, jackets, and travel accessories.',
    date: '2026-04-28T15:15:00.000Z',
    direction: 'inbound',
    labels: ['Promotions'],
  },
  {
    id: 'email_receipt',
    sender: 'Corner Market <receipts@cornermarket.example>',
    subject: 'Your receipt from Corner Market',
    body: 'Thanks for shopping with us. Your receipt for order CM-49281 is attached for your records.',
    date: '2026-04-28T02:10:00.000Z',
    direction: 'inbound',
    labels: ['Receipts'],
  },
  {
    id: 'email_sent_follow_up',
    sender: 'Me',
    subject: 'Proposal timeline and next steps',
    body: 'Hi Sam, sending over the proposal timeline we discussed. I will follow up Friday if I have not heard back.',
    date: '2026-04-27T20:00:00.000Z',
    direction: 'sent',
    labels: ['Work', 'Follow-up'],
  },
  {
    id: 'email_deadline_reminder',
    sender: 'City Recreation Portal <no-reply@cityrec.example>',
    subject: 'Reminder: summer camp registration closes May 1',
    body: 'Registration for summer camp closes on May 1 at 5 PM. Submit all required details before the deadline.',
    date: '2026-04-27T17:30:00.000Z',
    direction: 'inbound',
    labels: ['Family', 'Deadline'],
  },
  {
    id: 'email_trip_planning_1',
    sender: 'Maya Chen <maya@friends.example>',
    subject: 'Re: Portland trip planning',
    body: 'I can do the second weekend in May. If we want the riverfront place, we should decide by Friday before rates go up.',
    date: '2026-04-29T18:30:00.000Z',
    direction: 'inbound',
    labels: ['Travel', 'Conversation'],
    recipients: ['Me'],
  },
  {
    id: 'email_trip_planning_2',
    sender: 'Me',
    subject: 'Re: Portland trip planning',
    body: 'Second weekend works for me too. I can book the train once we pick the place to stay.',
    date: '2026-04-29T19:10:00.000Z',
    direction: 'sent',
    labels: ['Travel', 'Conversation'],
    recipients: [
      'Maya Chen <maya@friends.example>',
      'Sam Rivera <sam@friends.example>',
    ],
  },
  {
    id: 'email_trip_planning_3',
    sender: 'Maya Chen <maya@friends.example>',
    subject: 'Re: Portland trip planning',
    body: 'Let us go with the riverfront place. Can you book the train tonight and I will handle the reservation?',
    date: '2026-04-29T21:05:00.000Z',
    direction: 'inbound',
    labels: ['Travel', 'Conversation'],
    recipients: ['Me', 'Sam Rivera <sam@friends.example>'],
  },
  {
    id: 'email_project_discussion_1',
    sender: 'Jordan Lee <jordan@brightline.example>',
    subject: 'Re: Q2 launch scope',
    body: 'The launch scope still feels too broad. I think we should cut the partner dashboard from the first milestone.',
    date: '2026-04-28T17:20:00.000Z',
    direction: 'inbound',
    labels: ['Work', 'Conversation'],
    recipients: ['Me', 'Priya Shah <priya@brightline.example>'],
  },
  {
    id: 'email_project_discussion_2',
    sender: 'Me',
    subject: 'Re: Q2 launch scope',
    body: 'Agreed on narrowing scope. I would keep reporting in the launch but move partner dashboard to the next cycle.',
    date: '2026-04-28T18:05:00.000Z',
    direction: 'sent',
    labels: ['Work', 'Conversation'],
    recipients: [
      'Jordan Lee <jordan@brightline.example>',
      'Priya Shah <priya@brightline.example>',
    ],
  },
  {
    id: 'email_project_discussion_3',
    sender: 'Jordan Lee <jordan@brightline.example>',
    subject: 'Re: Q2 launch scope',
    body: 'That works. Can you update the launch notes with reporting kept in and partner dashboard moved out?',
    date: '2026-04-29T09:20:00.000Z',
    direction: 'inbound',
    labels: ['Work', 'Conversation'],
    recipients: ['Me', 'Priya Shah <priya@brightline.example>'],
  },
  {
    id: 'email_retreat_coordination_1',
    sender: 'Alex Kim <alex@studio.example>',
    subject: 'Re: Team retreat agenda',
    body: 'I pulled together a first agenda draft. We still need decisions on dinner, transport, workshop owners, and the budget cap.',
    date: '2026-04-30T09:15:00.000Z',
    direction: 'inbound',
    labels: ['Work', 'Conversation'],
    recipients: [
      'Me',
      'Maya Chen <maya@studio.example>',
      'Jordan Lee <jordan@studio.example>',
      'Priya Shah <priya@studio.example>',
      'Sam Rivera <sam@studio.example>',
      'Nina Rao <nina@studio.example>',
      'Omar Singh <omar@studio.example>',
      'Dana Wu <dana@studio.example>',
      'Chris Patel <chris@studio.example>',
    ],
  },
  {
    id: 'email_retreat_coordination_2',
    sender: 'Me',
    subject: 'Re: Team retreat agenda',
    body: 'The agenda looks good. I can own transport and budget. Can someone confirm dinner options and workshop leads?',
    date: '2026-04-30T10:00:00.000Z',
    direction: 'sent',
    labels: ['Work', 'Conversation'],
    recipients: [
      'Alex Kim <alex@studio.example>',
      'Maya Chen <maya@studio.example>',
      'Jordan Lee <jordan@studio.example>',
      'Priya Shah <priya@studio.example>',
      'Sam Rivera <sam@studio.example>',
      'Nina Rao <nina@studio.example>',
      'Omar Singh <omar@studio.example>',
      'Dana Wu <dana@studio.example>',
      'Chris Patel <chris@studio.example>',
    ],
  },
  {
    id: 'email_retreat_coordination_3',
    sender: 'Priya Shah <priya@studio.example>',
    subject: 'Re: Team retreat agenda',
    body: 'I can confirm dinner options by tomorrow. Maya and Jordan, can you send workshop owners today so we can close the agenda?',
    date: '2026-04-30T11:20:00.000Z',
    direction: 'inbound',
    labels: ['Work', 'Conversation'],
    recipients: [
      'Me',
      'Alex Kim <alex@studio.example>',
      'Maya Chen <maya@studio.example>',
      'Jordan Lee <jordan@studio.example>',
      'Sam Rivera <sam@studio.example>',
      'Nina Rao <nina@studio.example>',
      'Omar Singh <omar@studio.example>',
      'Dana Wu <dana@studio.example>',
      'Chris Patel <chris@studio.example>',
    ],
  },
]
