import type { Email } from '@/types/mail'

export const sampleEmails: Email[] = [
  {
    id: 'email_bill_due',
    sender: 'Pacific Utilities <billing@pacificutilities.example>',
    subject: 'Payment due for your April utility bill',
    body: 'Your April utility bill is due on May 5. Please submit payment before the due date to avoid a late fee.',
    date: '2026-04-29T15:20:00.000Z',
    direction: 'inbound',
    labels: ['Bills', 'Finance'],
  },
  {
    id: 'email_permission_slip',
    sender: 'Lincoln Elementary <office@lincolnelementary.example>',
    subject: 'Field trip permission slip due Friday',
    body: 'Please sign and return the attached permission slip for the science museum field trip by Friday morning.',
    date: '2026-04-29T14:05:00.000Z',
    direction: 'inbound',
    labels: ['School', 'Family'],
  },
  {
    id: 'email_delivery_issue',
    sender: 'Northstar Delivery <support@northstardelivery.example>',
    subject: 'Action required: delivery address issue',
    body: 'We could not complete delivery because the apartment number was missing. Reply with the corrected address within 24 hours.',
    date: '2026-04-29T13:10:00.000Z',
    direction: 'inbound',
    labels: ['Shipping'],
  },
  {
    id: 'email_event_rsvp',
    sender: 'Avery Kim <avery@neighborhood.example>',
    subject: 'RSVP for Saturday community dinner',
    body: 'Can you let me know by Thursday whether you can attend the community dinner this Saturday?',
    date: '2026-04-29T12:30:00.000Z',
    direction: 'inbound',
    labels: ['Events'],
  },
  {
    id: 'email_work_follow_up',
    sender: 'Jordan Lee <jordan@brightline.example>',
    subject: 'Follow-up on Q2 launch notes',
    body: 'Please review the Q2 launch notes and send your edits before our planning meeting tomorrow.',
    date: '2026-04-29T11:45:00.000Z',
    direction: 'inbound',
    labels: ['Work'],
  },
  {
    id: 'email_doctor_form',
    sender: 'Willow Creek Clinic <forms@willowcreekclinic.example>',
    subject: 'Complete intake form before your appointment',
    body: 'Your appointment is scheduled for May 3. Complete the intake form online at least 24 hours before arrival.',
    date: '2026-04-29T10:15:00.000Z',
    direction: 'inbound',
    labels: ['Health'],
  },
  {
    id: 'email_subscription_renewal',
    sender: 'CloudNotes <billing@cloudnotes.example>',
    subject: 'Your annual subscription renews soon',
    body: 'Your CloudNotes annual plan renews on May 8. Review your plan or update payment details before renewal.',
    date: '2026-04-28T18:40:00.000Z',
    direction: 'inbound',
    labels: ['Subscriptions'],
  },
  {
    id: 'email_newsletter',
    sender: 'The Product Brief <newsletter@productbrief.example>',
    subject: 'This week in AI productivity tools',
    body: 'Read our roundup of new product releases, workflow ideas, and interviews with teams adopting AI assistants.',
    date: '2026-04-28T16:25:00.000Z',
    direction: 'inbound',
    labels: ['Newsletter'],
  },
  {
    id: 'email_promotion',
    sender: 'Trail Supply Co. <deals@trailsupply.example>',
    subject: 'Spring sale: 30% off backpacks',
    body: 'Shop our spring sale this week and save on backpacks, jackets, and travel accessories.',
    date: '2026-04-28T15:15:00.000Z',
    direction: 'inbound',
    labels: ['Promotions'],
  },
  {
    id: 'email_receipt',
    sender: 'Corner Market <receipts@cornermarket.example>',
    subject: 'Your receipt from Corner Market',
    body: 'Thanks for shopping with us. Your receipt for order CM-49281 is attached for your records.',
    date: '2026-04-28T02:10:00.000Z',
    direction: 'inbound',
    labels: ['Receipts'],
  },
  {
    id: 'email_sent_follow_up',
    sender: 'Me',
    subject: 'Proposal timeline and next steps',
    body: 'Hi Sam, sending over the proposal timeline we discussed. I will follow up Friday if I have not heard back.',
    date: '2026-04-27T20:00:00.000Z',
    direction: 'sent',
    labels: ['Work', 'Follow-up'],
  },
  {
    id: 'email_sent_vendor_estimate',
    sender: 'Me',
    subject: 'Kitchen repair estimate',
    body: 'Hi Dana, could you send the updated kitchen repair estimate when you have a chance? I need it before I approve the work.',
    date: '2026-04-28T13:30:00.000Z',
    direction: 'sent',
    labels: ['Home'],
    recipients: ['Dana Repairs <dana@repairs.example>'],
  },
  {
    id: 'email_sent_parent_meeting',
    sender: 'Me',
    subject: 'Parent volunteer schedule',
    body: 'Hi Morgan, can you confirm whether I am still assigned to the Tuesday morning volunteer slot?',
    date: '2026-04-27T19:15:00.000Z',
    direction: 'sent',
    labels: ['School'],
    recipients: ['Morgan Lee <morgan@school.example>'],
  },
  {
    id: 'email_sent_caterer_question',
    sender: 'Me',
    subject: 'Caterer headcount question',
    body: 'Hi Priya, can you confirm the final headcount for the caterer so I can lock the order?',
    date: '2026-04-28T09:20:00.000Z',
    direction: 'sent',
    labels: ['Events'],
    recipients: ['Priya Shah <priya@events.example>'],
  },
  {
    id: 'email_caterer_question_reply',
    sender: 'Priya Shah <priya@events.example>',
    subject: 'Caterer headcount question',
    body: 'Yes, final headcount is 18. Please go ahead and lock the order with the caterer.',
    date: '2026-04-29T16:45:00.000Z',
    direction: 'inbound',
    labels: ['Events'],
    recipients: ['Me'],
  },
  {
    id: 'email_sent_fyi_notes',
    sender: 'Me',
    subject: 'FYI: neighborhood notes',
    body: 'Sharing the neighborhood meeting notes for your records. No action needed from anyone.',
    date: '2026-04-27T18:45:00.000Z',
    direction: 'sent',
    labels: ['FYI'],
    recipients: ['Avery Kim <avery@neighborhood.example>'],
  },
  {
    id: 'email_deadline_reminder',
    sender: 'City Recreation Portal <no-reply@cityrec.example>',
    subject: 'Reminder: summer camp registration closes May 1',
    body: 'Registration for summer camp closes on May 1 at 5 PM. Submit all required details before the deadline.',
    date: '2026-04-27T17:30:00.000Z',
    direction: 'inbound',
    labels: ['Family', 'Deadline'],
  },
  {
    id: 'email_insurance_documents',
    sender: 'Harbor Insurance <claims@harborinsurance.example>',
    subject: 'Action required: upload claim documents',
    body: 'Please submit the missing invoices and photos for claim HI-7721 by Thursday so we can continue processing your reimbursement.',
    date: '2026-04-30T08:05:00.000Z',
    direction: 'inbound',
    labels: ['Finance', 'Insurance'],
  },
  {
    id: 'email_library_renewal',
    sender: 'City Library <notices@citylibrary.example>',
    subject: 'Renew borrowed books before May 6',
    body: 'Your borrowed books are due soon. Renew the books or return them before May 6 to avoid late fees.',
    date: '2026-04-30T07:45:00.000Z',
    direction: 'inbound',
    labels: ['Family'],
  },
  {
    id: 'email_soccer_forms',
    sender: 'Riverside Soccer Club <admin@riversidesoccer.example>',
    subject: 'Please complete player medical form',
    body: 'Please complete the player medical form before practice tomorrow. Registration cannot be finalized until the form is submitted.',
    date: '2026-04-30T07:10:00.000Z',
    direction: 'inbound',
    labels: ['Family', 'Sports'],
  },
  {
    id: 'email_trip_planning_1',
    sender: 'Maya Chen <maya@friends.example>',
    subject: 'Re: Portland trip planning',
    body: 'I can do the second weekend in May. If we want the riverfront place, we should decide by Friday before rates go up.',
    date: '2026-04-29T18:30:00.000Z',
    direction: 'inbound',
    labels: ['Travel', 'Conversation'],
    recipients: ['Me'],
  },
  {
    id: 'email_trip_planning_2',
    sender: 'Me',
    subject: 'Re: Portland trip planning',
    body: 'Second weekend works for me too. I can book the train once we pick the place to stay.',
    date: '2026-04-29T19:10:00.000Z',
    direction: 'sent',
    labels: ['Travel', 'Conversation'],
    recipients: [
      'Maya Chen <maya@friends.example>',
      'Sam Rivera <sam@friends.example>',
    ],
  },
  {
    id: 'email_trip_planning_3',
    sender: 'Maya Chen <maya@friends.example>',
    subject: 'Re: Portland trip planning',
    body: 'Let us go with the riverfront place. Can you book the train tonight and I will handle the reservation?',
    date: '2026-04-29T21:05:00.000Z',
    direction: 'inbound',
    labels: ['Travel', 'Conversation'],
    recipients: ['Me', 'Sam Rivera <sam@friends.example>'],
  },
  {
    id: 'email_project_discussion_1',
    sender: 'Jordan Lee <jordan@brightline.example>',
    subject: 'Re: Q2 launch scope',
    body: 'The launch scope still feels too broad. I think we should cut the partner dashboard from the first milestone.',
    date: '2026-04-28T17:20:00.000Z',
    direction: 'inbound',
    labels: ['Work', 'Conversation'],
    recipients: ['Me', 'Priya Shah <priya@brightline.example>'],
  },
  {
    id: 'email_project_discussion_2',
    sender: 'Me',
    subject: 'Re: Q2 launch scope',
    body: 'Agreed on narrowing scope. I would keep reporting in the launch but move partner dashboard to the next cycle.',
    date: '2026-04-28T18:05:00.000Z',
    direction: 'sent',
    labels: ['Work', 'Conversation'],
    recipients: [
      'Jordan Lee <jordan@brightline.example>',
      'Priya Shah <priya@brightline.example>',
    ],
  },
  {
    id: 'email_project_discussion_3',
    sender: 'Jordan Lee <jordan@brightline.example>',
    subject: 'Re: Q2 launch scope',
    body: 'That works. Can you update the launch notes with reporting kept in and partner dashboard moved out?',
    date: '2026-04-29T09:20:00.000Z',
    direction: 'inbound',
    labels: ['Work', 'Conversation'],
    recipients: ['Me', 'Priya Shah <priya@brightline.example>'],
  },
  {
    id: 'email_retreat_coordination_1',
    sender: 'Alex Kim <alex@studio.example>',
    subject: 'Re: Team retreat agenda',
    body: 'I pulled together a first agenda draft. We still need decisions on dinner, transport, workshop owners, and the budget cap.',
    date: '2026-04-30T09:15:00.000Z',
    direction: 'inbound',
    labels: ['Work', 'Conversation'],
    recipients: [
      'Me',
      'Maya Chen <maya@studio.example>',
      'Jordan Lee <jordan@studio.example>',
      'Priya Shah <priya@studio.example>',
      'Sam Rivera <sam@studio.example>',
      'Nina Rao <nina@studio.example>',
      'Omar Singh <omar@studio.example>',
      'Dana Wu <dana@studio.example>',
      'Chris Patel <chris@studio.example>',
    ],
  },
  {
    id: 'email_retreat_coordination_2',
    sender: 'Me',
    subject: 'Re: Team retreat agenda',
    body: 'The agenda looks good. I can own transport and budget. Can someone confirm dinner options and workshop leads?',
    date: '2026-04-30T10:00:00.000Z',
    direction: 'sent',
    labels: ['Work', 'Conversation'],
    recipients: [
      'Alex Kim <alex@studio.example>',
      'Maya Chen <maya@studio.example>',
      'Jordan Lee <jordan@studio.example>',
      'Priya Shah <priya@studio.example>',
      'Sam Rivera <sam@studio.example>',
      'Nina Rao <nina@studio.example>',
      'Omar Singh <omar@studio.example>',
      'Dana Wu <dana@studio.example>',
      'Chris Patel <chris@studio.example>',
    ],
  },
  {
    id: 'email_retreat_coordination_3',
    sender: 'Priya Shah <priya@studio.example>',
    subject: 'Re: Team retreat agenda',
    body: 'I can confirm dinner options by tomorrow. Maya and Jordan, can you send workshop owners today so we can close the agenda?',
    date: '2026-04-30T11:20:00.000Z',
    direction: 'inbound',
    labels: ['Work', 'Conversation'],
    recipients: [
      'Me',
      'Alex Kim <alex@studio.example>',
      'Maya Chen <maya@studio.example>',
      'Jordan Lee <jordan@studio.example>',
      'Sam Rivera <sam@studio.example>',
      'Nina Rao <nina@studio.example>',
      'Omar Singh <omar@studio.example>',
      'Dana Wu <dana@studio.example>',
      'Chris Patel <chris@studio.example>',
    ],
  },
  {
    id: 'email_restaurant_plan_1',
    sender: 'Mona Patel <mona@friends.example>',
    subject: 'Re: Friday dinner reservation',
    body: 'I checked with the restaurant Olive House and they can hold a table for six at 7 PM if we confirm by tomorrow.',
    date: '2026-04-30T12:10:00.000Z',
    direction: 'inbound',
    labels: ['Events', 'Conversation'],
    recipients: ['Me', 'Leo Park <leo@friends.example>'],
  },
  {
    id: 'email_restaurant_plan_2',
    sender: 'Me',
    subject: 'Re: Friday dinner reservation',
    body: 'Olive House at 7 PM works for me. Can you confirm the reservation and ask whether they have a patio table?',
    date: '2026-04-30T12:35:00.000Z',
    direction: 'sent',
    labels: ['Events', 'Conversation'],
    recipients: [
      'Mona Patel <mona@friends.example>',
      'Leo Park <leo@friends.example>',
    ],
  },
  {
    id: 'email_budget_review_1',
    sender: 'Rina Gomez <rina@brightline.example>',
    subject: 'Re: Budget review notes',
    body: 'The April budget looks close to plan, but travel expenses need one more pass before we share the summary.',
    date: '2026-04-30T13:05:00.000Z',
    direction: 'inbound',
    labels: ['Work', 'Conversation'],
    recipients: ['Me'],
  },
  {
    id: 'email_budget_review_2',
    sender: 'Me',
    subject: 'Re: Budget review notes',
    body: 'I can clean up the travel category this afternoon. Can you send the latest vendor totals so I can reconcile the summary?',
    date: '2026-04-30T13:40:00.000Z',
    direction: 'sent',
    labels: ['Work', 'Conversation'],
    recipients: ['Rina Gomez <rina@brightline.example>'],
  },
  {
    id: 'email_neighbor_outing_1',
    sender: 'Avery Kim <avery@neighborhood.example>',
    subject: 'Re: Neighborhood outing',
    body: 'The park pavilion is available on Saturday morning, and I can bring the sign-up sheet.',
    date: '2026-04-30T14:20:00.000Z',
    direction: 'inbound',
    labels: ['Events', 'Conversation'],
    recipients: ['Me', 'Nina Rao <nina@neighborhood.example>'],
  },
  {
    id: 'email_neighbor_outing_2',
    sender: 'Nina Rao <nina@neighborhood.example>',
    subject: 'Re: Neighborhood outing',
    body: 'Saturday morning works. I can coordinate snacks if someone else handles the supplies list.',
    date: '2026-04-30T14:55:00.000Z',
    direction: 'inbound',
    labels: ['Events', 'Conversation'],
    recipients: ['Me', 'Avery Kim <avery@neighborhood.example>'],
  },
  {
    id: 'email_whole_foods_delivery',
    sender: 'Whole Foods Market <orders@wholefoods.example>',
    subject: 'Your Whole Foods delivery was delivered',
    body: 'Your Whole Foods Market order WF-1048 was delivered at 6:42 PM. Order total: $86.42. Items: organic bananas $4.29; oat milk $5.49; kale salad $12.99; sourdough bread $6.75; pantry staples $56.90.',
    date: '2026-04-30T18:42:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Delivery', 'Transactions'],
  },
  {
    id: 'email_instacart_order',
    sender: 'Instacart <orders@instacart.example>',
    subject: 'Your Instacart order is out for delivery',
    body: 'Your Instacart order IC-8831 from Safeway is out for delivery and should arrive today by 5:15 PM. Order total: $64.18. Items: eggs $6.49; coffee $14.99; spinach $4.79; pasta sauce $5.49; household items $32.42.',
    date: '2026-04-30T15:05:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Delivery', 'Transactions'],
  },
  {
    id: 'email_amazon_shipment',
    sender: 'Amazon.com <shipment-tracking@amazon.example>',
    subject: 'Your Amazon package has shipped',
    body: 'Your Amazon order 113-7429931-0056208 has shipped. Tracking number: TBA92837465. Estimated delivery: May 2. Items: USB-C hub $24.99; laptop stand $23.98. Order total: $48.97.',
    date: '2026-04-30T08:35:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Shipping', 'Transactions'],
  },
  {
    id: 'email_refund_confirmation',
    sender: 'Instacart <refunds@instacart.example>',
    subject: 'Refund confirmation for your Instacart order',
    body: 'We issued a refund of $12.49 for unavailable strawberries on order IC-8831. The refund should appear on your original payment method within 3-5 business days.',
    date: '2026-04-30T19:10:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Refunds', 'Transactions'],
  },
  {
    id: 'email_replacement_notice',
    sender: 'Whole Foods Market <orders@wholefoods.example>',
    subject: 'Item replacement in your Whole Foods order',
    body: 'Organic strawberries were unavailable in order WF-1048. We replaced them with organic blueberries at no extra charge. Price difference: $0.00.',
    date: '2026-04-30T17:55:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Replacements', 'Transactions'],
  },
  {
    id: 'email_whole_foods_second_order',
    sender: 'Whole Foods Market <orders@wholefoods.example>',
    subject: 'Your Whole Foods pickup order is ready',
    body: 'Your Whole Foods Market order WF-20491 is confirmed and ready for pickup today by 7:30 PM. Order total: $42.15. Items: sparkling water $8.99; hummus $5.49; pita chips $4.99; blueberries $7.99; prepared foods $14.69.',
    date: '2026-05-01T16:15:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Delivery', 'Transactions'],
  },
  {
    id: 'email_payment_receipt',
    sender: 'DoorDash <receipts@doordash.example>',
    subject: 'Payment receipt for your DoorDash order',
    body: 'Your payment for DoorDash order DD-4102 is confirmed. Order total: $37.26. Merchant: Thai Garden. Items: pad thai $16.50; spring rolls $8.25; jasmine rice $3.50; fees and tip $9.01.',
    date: '2026-04-29T20:25:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Receipts', 'Transactions'],
  },
  {
    id: 'email_target_pickup',
    sender: 'Target <orders@target.example>',
    subject: 'Your Target order is ready for pickup',
    body: 'Your Target order TG-6621 is confirmed and ready for pickup today by 8:00 PM. Order total: $29.34. Items: storage bins $18.00; dish soap $4.49; notebook $6.85.',
    date: '2026-04-30T12:05:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Delivery', 'Transactions'],
  },
  {
    id: 'email_gap_shipment',
    sender: 'Gap <orders@gap.example>',
    subject: 'Your Gap order has shipped',
    body: 'Your Gap order GP-4482 has shipped. Tracking number: 1Z999AA10123456784. Estimated delivery: May 3. Items: slim jeans $54.95; cotton tee $19.95; shipping $5.00. Order total: $79.90.',
    date: '2026-04-30T10:45:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Shipping', 'Transactions'],
  },
  {
    id: 'email_ulta_pickup',
    sender: 'Ulta Beauty <orders@ulta.example>',
    subject: 'Your Ulta Beauty order is ready for pickup',
    body: 'Your Ulta Beauty order UL-2209 is confirmed and ready for pickup today by 6:00 PM. Order total: $46.72. Items: mascara $14.99; cleanser $18.00; cotton pads $5.49; tax $8.24.',
    date: '2026-04-30T13:40:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Delivery', 'Transactions'],
  },
  {
    id: 'email_sephora_delivery',
    sender: 'Sephora <orders@sephora.example>',
    subject: 'Your Sephora order was delivered',
    body: 'Your Sephora order SE-7816 was delivered at 2:12 PM. Order total: $68.35. Items: moisturizer $38.00; lip balm $12.00; sunscreen $18.35.',
    date: '2026-04-30T14:12:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Delivery', 'Transactions'],
  },
  {
    id: 'email_etsy_shipment',
    sender: 'Etsy <transaction@etsy.example>',
    subject: 'Your Etsy order has shipped',
    body: 'Your Etsy order ET-5938 has shipped. Tracking number: 9400110200881234567890. Estimated delivery: May 4. Items: ceramic mug $32.00; shipping $6.50. Order total: $38.50.',
    date: '2026-04-29T22:10:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Shipping', 'Transactions'],
  },
  {
    id: 'email_chewy_delivery',
    sender: 'Chewy <orders@chewy.example>',
    subject: 'Your Chewy order was delivered',
    body: 'Your Chewy order CH-7715 was delivered at 3:18 PM. Order total: $57.88. Items: dog food $42.99; treats $8.99; waste bags $5.90.',
    date: '2026-04-30T15:18:00.000Z',
    direction: 'inbound',
    labels: ['Orders', 'Delivery', 'Transactions'],
  },
]
